### ISSUE TITLE
Open a steam shortcut

### ISSUE THREAD

**Issue by Yvanovitch** [sindresorhus/open-shortcut#2]
Hi, it works well for a url shortcut like "http://google.com" but I tried it to run a steam game with the following url "steam://rungameid/550"
I have the message: 
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot
perty 'trim' of undefined
Is there anything specific I should have done?
Thanks

**Comment by kevva** [comment]
That's because `steam://rungameid/550` isn't a valid URL according to https://github.com/kevva/url-regex/.

**Comment by Yvanovitch** [comment]
Alright, I'm not going to push further because I found another way to run the same command:
`var gameProcess = child_process.exec('explorer steam://run/550', function(error, stdout, stderr) {
    console.log('test '+stdout);
});`
However, in the future it's possible that someone might want to execute such a shortcut, who knows
Anyway, thanks for the fast reply
